---
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, lf]
      # TODO this doesn't work when CI runs on the default branch.
      # - id: no-commit-to-branch
      #   args: [--branch, main, --branch, master, --branch, devel, --branch, develop]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format-and-lint
        name: format-and-lint
        entry: hatch run format-and-lint:all
        language: python
        types: [python]
        verbose: true
        require_serial: true
