name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
