name: Labeler

on:
  push:
    branches:
      - main
      - master

permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@31674a3852a9074f2086abcf1c53839d466a47e7 # v5.2.0
        with:
          skip-delete: true
